export type ScenarioId = "pior" | "ruim" | "medio" | "medio_otimista" | "otimista";

export type CalculatorAssumptions = {
  scenario: ScenarioId;
  fleet: {
    totalCars: number;
    occupancyRate: number;
    monthlyVehicleRental: number;
    insurancePerCar: number;
    telemetryPerCar: number;
    maintenancePerCar: number;
    cleaningPerCar: number;
    yardPerCar: number;
    adminPerCar: number;
    driverHoursPerDay: number;
    monthlyKmPerDriver: number;
    monthlyKmAllowance: number;
    extraKmFee: number;
    gasolineCostPerKm: number;
    electricCostPerKm: number;
    downtimeRate: number;
    avgStoppedDays: number;
    incidentRate: number;
    avgIncidentCost: number;
    chargingIncluded: boolean;
  };
  offer: {
    dailyPrice: number;
    weeklyPrice: number;
    monthlyPrice: number;
    activationFee: number;
    entryFee: number;
    averageContractMonths: number;
    churnRate: number;
    defaultRate: number;
    defaultRecoveryRate: number;
    averageDiscountRate: number;
    additionalRevenuePerDriver: number;
  };
  marketing: {
    cpl: number;
    monthlyMediaSpend: number;
    leadToWhatsappRate: number;
    whatsappToWebinarRate: number;
    attendanceRate: number;
    applicationRate: number;
    approvalRate: number;
    closeRate: number;
    activationRate: number;
    launchProductionCost: number;
    toolsCost: number;
    agencyCost: number;
  };
  sales: {
    leadsPerSdr: number;
    opportunitiesPerCloser: number;
    sdrSalary: number;
    closerSalary: number;
    commissionPerContract: number;
    salesManagerSalary: number;
    manualSdrs: number;
    manualClosers: number;
  };
  operations: {
    ticketsPerDriver: number;
    ticketsPerAgent: number;
    supportAgentSalary: number;
    carsPerFleetManager: number;
    fleetManagerSalary: number;
    deliveriesPerOperator: number;
    operatorSalary: number;
    applicationsPerCreditAnalyst: number;
    creditAnalystSalary: number;
    collectionCost: number;
    vehicleRecoveryCost: number;
    fixedAdminCost: number;
    legalComplianceCost: number;
    technologyCost: number;
  };
  credit: {
    consortiumInterestRate: number;
    consortiumConversionRate: number;
    consortiumCommission: number;
    creditPartnerRevenue: number;
    entrySignalClientRate: number;
    averageEntrySignal: number;
    complianceCostPerOperation: number;
    riskProvisionRate: number;
    cancellationRate: number;
  };
  financing: {
    ownershipConversionRate: number;
    downPaymentMin: number;
    downPaymentMax: number;
    retainedDownPaymentRate: number;
    monthlyInstallment: number;
    retainedInstallmentRate: number;
    installmentTermMonths: number;
    deliveryLeadMonths: number;
    cohortSize: number;
    cohortCadenceMonths: number;
    activeInstallmentContracts: number;
  };
  taxes: {
    revenueTaxRate: number;
    profitTaxRate: number;
    initialCash: number;
    cashReserveMonths: number;
  };
};

export type CalculatorResults = {
  fleet: {
    activeCars: number;
    inactiveCars: number;
    totalFleetCost: number;
    averageCostPerCar: number;
    lostRevenueFromDowntime: number;
    monthlyEnergySavingsForDrivers: number;
    incidentProvision: number;
    extraKmPerDriver: number;
    extraKmCost: number;
  };
  funnel: {
    leads: number;
    whatsapp: number;
    webinar: number;
    applications: number;
    approved: number;
    contracts: number;
    activatedContracts: number;
    requiredMediaToFillFleet: number;
    cacMarketing: number;
    roas: number;
  };
  financing: {
    newOwnershipContracts: number;
    bridgeCarsInUse: number;
    rentalOnlyCars: number;
    deliveredInstallmentContracts: number;
    installmentContracts: number;
    averageDownPayment: number;
    downPaymentCash: number;
    installmentRevenue: number;
    cycleDownPaymentCash: number;
    annualOwnershipDeliveries: number;
    releasedCarsPerCycle: number;
  };
  team: {
    sdrs: number;
    closers: number;
    supportAgents: number;
    fleetManagers: number;
    operators: number;
    creditAnalysts: number;
    salesCost: number;
    supportOpsCost: number;
  };
  dre: {
    recurringRevenue: number;
    activationRevenue: number;
    entryRevenue: number;
    complementaryRevenue: number;
    grossRevenue: number;
    deductions: number;
    netRevenue: number;
    directCosts: number;
    grossMargin: number;
    marketingCost: number;
    salesCost: number;
    supportOpsCost: number;
    adminCost: number;
    provisions: number;
    ebitda: number;
    profitTax: number;
    netProfit: number;
    cashNeed: number;
    cashAfterMonth: number;
  };
  unit: {
    revenuePerActiveCar: number;
    contributionPerCar: number;
    breakEvenCars: number | null;
    ltv: number;
    cacTotal: number;
    ltvCac: number;
    paybackMonths: number;
    ebitdaMargin: number;
  };
  projection: {
    month: number;
    activeCars: number;
    rentalOnlyCars: number;
    bridgeCarsInUse: number;
    installmentContracts: number;
    financingCash: number;
    grossRevenue: number;
    netRevenue: number;
    directCosts: number;
    marketingCost: number;
    salesCost: number;
    supportOpsCost: number;
    adminCost: number;
    ebitda: number;
    netProfit: number;
    cashAfterMonth: number;
  }[];
  alerts: string[];
};
